// <auto-generated />
namespace CMS.Migrations.CmsConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removeSubPage4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeSubPage4));
        
        string IMigrationMetadata.Id
        {
            get { return "201806111746463_removeSubPage4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
